### ISSUE TITLE
控件不能绑定单一的一个ImageView，位置在父控件位置，还是说你这个本来就只是给软件icon使用的？

### ISSUE THREAD

**Issue by love-311** [AlexLiuSheng/BadgeView#3]

**Comment by SunOfBeach2** [comment]
需要绑定的view必须要有个父控件

**Comment by love-311** [comment]
如果我要调整小红点的位置呢，比如右上角我想让他再靠右一些呢？

**Comment by SunOfBeach2** [comment]
暂时不行，后续版本可能会支持

**Comment by SunOfBeach2** [comment]
v1.0.5 支持设置margin了

**Comment by love-311** [comment]
刚刚尝试了一下发现这个margin是在移动本身的控件呀，不是红点在移动。。你是不是搞错了呀。。-。-

**Comment by SunOfBeach2** [comment]
--这个应该是相对的吧，确实是设置的view的margin，但是设置margin相对的也在移动badge，因为设置margin不可避免的 整个view宽高会改变。setMargin(0,0,5,0)应该可以达到你想要的效果

**Comment by love-311** [comment]
我觉得badgeView应该是固定绑定一个view，然后以那个View为基准，而不应该以它的父控件为基准。在前面的条件下，我是通过约束布局的控件达到了我想要的效果，刚刚我试了你新加的属性，的确是导致我的控件产生移动，而红点位置并没有改变。
